### ISSUE TITLE
Improving Amaze Demosaicing Speed

### ISSUE THREAD

**Issue by TimZaman** [LibRaw/LibRaw-demosaic-pack-GPL3#1]
Hi. I am currently busy improving the amaze efficiency as was done over the years in rawtherapee. I have come a long way, and just like rawtherapee i am able to get a very consistent 30% speed increase with the exact same pixel result. 
However, the final step is using SSE2, for which they use pointers to floats. Am i correct in thinking 'we' with libraw use (what was it?) unsigned short's, for the 'image' variable.?
I'm now kind of puzzled of how i would correctly use an important SSE function like `_mm_loadu_ps(&pixelDataPoint)`.
Any ideas?

**Comment by LibRaw** [comment]
Yes, libraw uses 16-bit unsigned short image[][] array.

**Comment by LibRaw** [comment]
Libraw demosaics packs are not supported since LibRaw 0.19, so the issue is closed.

Hope someone will pick up this code
