### ISSUE TITLE
Get newer version of auto CA correction and AMaZE

### ISSUE THREAD

**Issue by CarVac** [LibRaw/LibRaw-demosaic-pack-GPL3#2]
The versions of auto CA correction and AMaZE here are quite old, and in the meantime plenty of work has occurred on them in RawTherapee.

For example, apparently the auto CA correction here has a race condition due to reuse of an array, and so occasionally it gives noticeably incorrect results when the same image loaded in RawTherapee has no issues.

Additionally, both AMaZE and auto CA correction have been optimized and sped up a lot.

Would you be able to update these to newer versions? I'd be able to help out with this if you can guide me on what the inputs and outputs are.

(Also, the LMMSE implementation has been greatly sped up in RawTherapee, with multi-threading, and that might be worth moving it from the GPL2 to the GPL3 demosaic pack)

(Another also, the X-trans implementation has also been improved, and maybe there could be the current slow version in the main repository and a fast version here in the GPL3 demosaic pack)

**Comment by LibRaw** [comment]
In LibRaw project we're focused on raw data and metadata decoding, no plans to change/improve postprocessing stage for now.

We're open to user patches/contributions, so if you'll port RawTherapee code to LibRaw's 'demosaic pack' we'll accept these changes in master.

**Comment by LibRaw** [comment]
Libraw demosaics packs are not supported since LibRaw 0.19, so the issue is closed.

Hope someone will pick up this code

**Comment by CarVac** [comment]
This is fine. I've started [librtprocess](https://github.com/CarVac/librtprocess) in order to share the raw processing algorithms that come after decoding.
